#!/bin/bash
# ─────────────────────────────────────────────────────────
# push_to_github.sh
# Run this once from inside the heart-disease-ml/ folder
# to initialise git and push to a new GitHub repo.
#
# Prerequisites:
#   1. GitHub CLI installed: https://cli.github.com
#   2. Logged in: gh auth login
# ─────────────────────────────────────────────────────────

set -e

REPO_NAME="heart-disease-ml"
DESCRIPTION="End-to-end heart disease prediction ML pipeline (built by Claude / Anthropic)"

echo "→ Initialising git..."
git init
git add .
git commit -m "Initial commit: full E2E heart disease ML pipeline

Generated by Claude (Anthropic). Includes:
- Data loading, cleaning & feature engineering
- EDA with 11 visualisation plots
- 5 models trained with GridSearchCV tuning
- Full evaluation (ROC, PR, confusion matrices, feature importance)
- Inference module with example patients
- 23 unit tests (all passing)"

echo "→ Creating GitHub repo and pushing..."
gh repo create "$REPO_NAME" \
  --public \
  --description "$DESCRIPTION" \
  --source=. \
  --remote=origin \
  --push

echo ""
echo "✅ Done! Your repo is live at:"
gh repo view --web 2>/dev/null || echo "  https://github.com/$(gh api user -q .login)/$REPO_NAME"
